### ISSUE TITLE
Possible two grant votes from single node in single term

### ISSUE THREAD

**Issue by bakwc** [ZhukovAlexander/rafter#1]
When granting vote, leader does not store it in voted_for. Also he doesn't perform log comparison.

**Comment by ZhukovAlexander** [comment]
1. Technically, leader will not vote for anybody except self, so this situation wan't happen
2. LMDB doesn't support compression out of the box. So log compaction is an open question as of now

**Comment by bakwc** [comment]
> Technically, leader will not vote for anybody except self

Now seems ok.

> Also he doesn't perform log comparison.

I mean, there was no `self.log.cmp(last_log_index, last_log_term)` check. Now it seems to be fixed.
